# -*- coding: utf-8 -*-

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fGIO5EFwUNqwiI4CnWxW0A8nz75-35Ao
"""



"""# Task
Analyze air quality data by detecting anomalies, categorizing pollution levels, training and evaluating supervised classification models, and investigating the impact of anomalies on prediction model robustness.

## Load Air Quality Data

### Subtask:
Load the provided Air Quality Dataset into a pandas DataFrame. The data should be ready for initial inspection and processing. If a specific file path is not given, I will assume a common format like CSV.

### Subtask Instructions

1.  **Import pandas**: Import the pandas library, which is essential for data manipulation in Python.
    ```python
    import pandas as pd
    ```
2.  **Load the Dataset**: Load the air quality dataset into a pandas DataFrame. Since a specific file path is not provided, I will assume a CSV format and use a placeholder filename `air_quality_data.csv`. You should replace `'air_quality_data.csv'` with the actual path to your dataset file.
    ```python
    df = pd.read_csv('air_quality_data.csv')
    ```
3.  **Inspect Data - Head**: Display the first few rows of the DataFrame to quickly inspect its structure and content.
    ```python
    df.head()
    ```
4.  **Inspect Data - Info**: Display the column names and their data types, along with non-null counts, to understand the data's composition and identify potential issues.
    ```python
    df.info()
    ```

**Reasoning**:
Now, I will execute the steps outlined in the instructions to load the dataset, import pandas, and display its head and info, assuming 'air_quality_data.csv' as the filename.
"""

import pandas as pd

# Load the dataset. Replace 'air_quality_data.csv' with the actual path to your dataset file.
# If the file does not exist in the current directory, this will raise a FileNotFoundError.
df = pd.read_csv('air_quality_data.csv')

# Display the first few rows of the DataFrame
print("First 5 rows of the DataFrame:")
print(df.head())

# Display column names, their data types, and non-null counts
print("\nDataFrame Info:")
df.info()

"""**Reasoning**:
The previous attempt to load `air_quality_data.csv` failed because the file was not found. To resolve this, I will create a dummy CSV file with sample data to ensure the `pd.read_csv()` function has a file to load.


"""

import pandas as pd
import numpy as np

# Create dummy data for air quality
dates = pd.date_range(start='2023-01-01', periods=100, freq='H')
data = {
    'Timestamp': dates,
    'PM2.5': np.random.uniform(10, 50, 100),
    'PM10': np.random.uniform(20, 100, 100),
    'NO2': np.random.uniform(5, 30, 100),
    'SO2': np.random.uniform(1, 15, 100),
    'CO': np.random.uniform(0.1, 5, 100),
    'O3': np.random.uniform(20, 80, 100)
}
dummy_df = pd.DataFrame(data)

# Save the dummy DataFrame to a CSV file
dummy_df.to_csv('air_quality_data.csv', index=False)

print("Created 'air_quality_data.csv' with dummy data.")

# Load the dataset.
df = pd.read_csv('air_quality_data.csv')

# Display the first few rows of the DataFrame
print("\nFirst 5 rows of the DataFrame:")
print(df.head())

# Display column names, their data types, and non-null counts
print("\nDataFrame Info:")
df.info()

"""**Reasoning**:
The 'Timestamp' column was loaded as an object type, but for time-series analysis, it needs to be converted to a datetime object. I will convert this column to the correct datetime format and then set it as the DataFrame's index for easier time-based operations.


"""

df['Timestamp'] = pd.to_datetime(df['Timestamp'])
df = df.set_index('Timestamp')

print("DataFrame after converting 'Timestamp' to datetime and setting as index:")
df.info()
print("\nFirst 5 rows of the DataFrame after setting Timestamp as index:")
print(df.head())

"""## Preprocess Data

### Subtask:
Perform essential preprocessing steps, including handling missing values (e.g., imputation or removal) and normalizing numerical features to ensure consistent scaling for machine learning models.

## Preprocess Data

### Subtask:
Perform essential preprocessing steps, including handling missing values (e.g., imputation or removal) and normalizing numerical features to ensure consistent scaling for machine learning models.

#### Instructions
1. Check for missing values in the DataFrame `df` using `.isnull().sum()` to identify any columns with missing data. If missing values are present, decide on an appropriate strategy (e.g., imputation with the mean/median, forward-fill, or dropping rows/columns) and apply it. For time-series data, forward-fill (`.ffill()`) or interpolation can be suitable options. For this dataset, if missing values are found, consider imputing them with the mean of their respective columns.
2. Identify all numerical feature columns in `df` that are not the index. These are the columns representing air quality measurements (e.g., 'PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'O3').
3. Import `StandardScaler` from `sklearn.preprocessing`.
4. Initialize `StandardScaler`.
5. Apply `StandardScaler` to the identified numerical feature columns in `df`. Store the scaled data back into the DataFrame, replacing the original unscaled columns. Ensure that the original DataFrame's index is preserved during this process.

**Reasoning**:
I need to perform the preprocessing steps as outlined in the instructions. The first step is to check for and handle any missing values in the DataFrame. I will print the sum of null values for each column and then fill them with the mean if any are found.
"""

print("Missing values before handling:\n", df.isnull().sum())

# Impute missing values with the mean of their respective columns
# Although the dummy data does not have missing values, this step is included
# to fulfill the instruction requirement for handling potential missing values.
df_imputed = df.fillna(df.mean(numeric_only=True))

print("\nMissing values after handling:\n", df_imputed.isnull().sum())

"""**Reasoning**:
The previous step successfully handled missing values. Now, I will proceed to normalize the numerical features using `StandardScaler` as per the instructions. This involves identifying the numerical columns, importing `StandardScaler`, initializing it, and then applying it to the features.


"""

from sklearn.preprocessing import StandardScaler

# Identify numerical feature columns (all columns except the index)
numerical_cols = df_imputed.columns.tolist()

# Initialize StandardScaler
scaler = StandardScaler()

# Apply StandardScaler to the numerical feature columns
df_scaled_array = scaler.fit_transform(df_imputed[numerical_cols])

# Create a new DataFrame with scaled data, preserving the original index and columns
df_scaled = pd.DataFrame(df_scaled_array, columns=numerical_cols, index=df_imputed.index)

# Display the first few rows of the scaled DataFrame
print("\nFirst 5 rows of the scaled DataFrame:")
print(df_scaled.head())

# Display descriptive statistics of the scaled DataFrame to verify scaling
print("\nDescriptive statistics of the scaled DataFrame:")
print(df_scaled.describe())

"""## Anomaly Detection (DBSCAN)

### Subtask:
Apply DBSCAN (Density-Based Spatial Clustering of Applications with Noise) to identify abnormal pollution patterns within the preprocessed dataset. Visualize the detected anomalies.

**Reasoning**:
I need to import the `DBSCAN` and `PCA` classes for anomaly detection and visualization, respectively, as per the instructions.
"""

from sklearn.cluster import DBSCAN
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns

print("Imported DBSCAN, PCA, matplotlib.pyplot, and seaborn.")

"""**Reasoning**:
Now that the required libraries are imported, I will initialize DBSCAN, apply it to the scaled DataFrame to identify anomalies, and then use PCA to reduce dimensionality for visualization. Finally, I will plot the results to show the detected anomalies.


"""

dbscan = DBSCAN(eps=0.5, min_samples=5)
df_scaled['dbscan_label'] = dbscan.fit_predict(df_scaled[numerical_cols])

# Reduce dimensionality for visualization using PCA
pca = PCA(n_components=2)
df_pca = pca.fit_transform(df_scaled[numerical_cols])
df_pca = pd.DataFrame(df_pca, columns=['PC1', 'PC2'], index=df_scaled.index)
df_pca['dbscan_label'] = df_scaled['dbscan_label']

# Visualize the anomalies
plt.figure(figsize=(10, 7))
sns.scatterplot(
    x='PC1', y='PC2', hue='dbscan_label', data=df_pca,
    palette='viridis', legend='full', s=100
)
plt.title('DBSCAN Anomaly Detection (PCA-reduced data)')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.show()

print(f"Number of anomalies detected: {len(df_scaled[df_scaled['dbscan_label'] == -1])}")

"""### Interpreting DBSCAN Results and Parameter Tuning

The previous DBSCAN application labeled all 100 data points as anomalies (`dbscan_label == -1`). This indicates that with `eps=0.5` and `min_samples=5`, no dense clusters were formed, and every point was considered noise. This is a common issue with DBSCAN, especially when dealing with synthetic or small datasets, or when the data distribution doesn't align with the chosen parameters.

**To effectively detect anomalies with DBSCAN, careful tuning of `eps` and `min_samples` is crucial.**

*   **`eps` (epsilon)**: The maximum distance between two samples for one to be considered as in the neighborhood of the other. A smaller `eps` means points must be closer to each other to be considered part of the same cluster. If `eps` is too small, all points might be labeled as noise. If `eps` is too large, all points might be in the same cluster.
*   **`min_samples`**: The number of samples (or total weight) in a neighborhood for a point to be considered as a core point. This includes the point itself. A higher `min_samples` value requires more points to form a dense region, making it harder for points to form clusters and thus potentially increasing the number of points classified as noise.

Given that all points were labeled as anomalies, we need to **increase `eps` or decrease `min_samples` (or both)** to allow for the formation of clusters. A common approach to determine a suitable `eps` value is to use a k-distance graph (where k is `min_samples`), plotting the distance of each point to its k-th nearest neighbor and looking for an 'elbow' point.

For the purpose of this demonstration, we will try adjusting these parameters to see if we can identify some points as part of a cluster and others as anomalies.

### Interpreting DBSCAN Results and Parameter Tuning

The previous DBSCAN application labeled all 100 data points as anomalies (`dbscan_label == -1`). This indicates that with `eps=0.5` and `min_samples=5`, no dense clusters were formed, and every point was considered noise. This is a common issue with DBSCAN, especially when dealing with synthetic or small datasets, or when the data distribution doesn't align with the chosen parameters.

**To effectively detect anomalies with DBSCAN, careful tuning of `eps` and `min_samples` is crucial.**

*   **`eps` (epsilon)**: The maximum distance between two samples for one to be considered as in the neighborhood of the other. A smaller `eps` means points must be closer to each other to be considered part of the same cluster. If `eps` is too small, all points might be labeled as noise. If `eps` is too large, all points might be in the same cluster.
*   **`min_samples`**: The number of samples (or total weight) in a neighborhood for a point to be considered as a core point. This includes the point itself. A higher `min_samples` value requires more points to form a dense region, making it harder for points to form clusters and thus potentially increasing the number of points classified as noise.

Given that all points were labeled as anomalies, we need to **increase `eps` or decrease `min_samples` (or both)** to allow for the formation of clusters. A common approach to determine a suitable `eps` value is to use a k-distance graph (where k is `min_samples`), plotting the distance of each point to its k-th nearest neighbor and looking for an 'elbow' point.

For the purpose of this demonstration, we will try adjusting these parameters to see if we can identify some points as part of a cluster and others as anomalies.

**Reasoning**:
Based on the explanation of DBSCAN parameter tuning, I will now re-run DBSCAN with adjusted parameters to illustrate how different settings can lead to the detection of clusters and a more reasonable number of anomalies. I will increase the `eps` value to allow for larger neighborhoods and potentially decrease `min_samples`.
"""

dbscan_tuned = DBSCAN(eps=1.5, min_samples=3) # Adjusted parameters
df_scaled['dbscan_label_tuned'] = dbscan_tuned.fit_predict(df_scaled[numerical_cols])

# Reduce dimensionality for visualization using PCA (using the same PCA transformation as before for consistency)
df_pca_tuned = df_pca.copy() # Start with the previous PCA results
df_pca_tuned['dbscan_label'] = df_scaled['dbscan_label_tuned']

# Visualize the anomalies with tuned parameters
plt.figure(figsize=(10, 7))
sns.scatterplot(
    x='PC1', y='PC2', hue='dbscan_label', data=df_pca_tuned,
    palette='viridis', legend='full', s=100
)
plt.title('DBSCAN Anomaly Detection with Tuned Parameters (PCA-reduced data)')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.show()

print(f"Number of anomalies detected with tuned parameters: {len(df_scaled[df_scaled['dbscan_label_tuned'] == -1])}")

"""## Create Pollution Categories

### Subtask:
Based on pollution level features, create discrete pollution categories: 'Low', 'Moderate', and 'High'. This will transform the problem into a multi-class classification task. Visualize the distribution of these new categories.

**Reasoning**:
I need to define pollution categories based on the scaled air quality metrics. First, I will calculate an average pollution metric from the numerical columns in `df_scaled`. Then, I will use quantiles to define the 'Low', 'Moderate', and 'High' thresholds for this average metric.
"""

import numpy as np

# Calculate an average pollution metric from the numerical columns
# using all columns in df_scaled, as they are all numerical and represent pollution metrics
selected_metrics = numerical_cols # Use all scaled numerical columns
df_scaled['average_pollution'] = df_scaled[selected_metrics].mean(axis=1)

# Define thresholds using quantiles for 'Low', 'Moderate', and 'High' categories
low_threshold = df_scaled['average_pollution'].quantile(0.33)
moderate_threshold = df_scaled['average_pollution'].quantile(0.66)

print(f"Low pollution threshold (33rd percentile): {low_threshold:.2f}")
print(f"Moderate pollution threshold (66th percentile): {moderate_threshold:.2f}")

# Display the first few rows with the new average_pollution column
print("\nFirst 5 rows of df_scaled with 'average_pollution':")
print(df_scaled.head())

"""**Reasoning**:
Now that the thresholds are defined, I will categorize the 'average_pollution' into 'Low', 'Moderate', and 'High' and store these categories in a new column. Then, I will visualize the distribution of these categories using a count plot.


"""

import matplotlib.pyplot as plt
import seaborn as sns

# Create 'pollution_category' based on thresholds
def categorize_pollution(avg_pollution):
    if avg_pollution <= low_threshold:
        return 'Low'
    elif avg_pollution <= moderate_threshold:
        return 'Moderate'
    else:
        return 'High'

df_scaled['pollution_category'] = df_scaled['average_pollution'].apply(categorize_pollution)

# Display the count of each category
print("\nDistribution of Pollution Categories:")
print(df_scaled['pollution_category'].value_counts())

# Visualize the distribution of the new categories
plt.figure(figsize=(8, 6))
sns.countplot(x='pollution_category', data=df_scaled, palette='viridis', order=['Low', 'Moderate', 'High'])
plt.title('Distribution of Pollution Categories')
plt.xlabel('Pollution Level')
plt.ylabel('Count')
plt.show()

# Display the first few rows of the DataFrame with the new category column
print("\nFirst 5 rows of df_scaled with 'pollution_category':")
print(df_scaled.head())

"""**Reasoning**:
The previous code produced a `FutureWarning` regarding the use of `palette` without `hue` in `sns.countplot`. To address this, I will explicitly set `hue='pollution_category'` and `legend=False` in the `countplot` function call.


"""

import matplotlib.pyplot as plt
import seaborn as sns

# Create 'pollution_category' based on thresholds
def categorize_pollution(avg_pollution):
    if avg_pollution <= low_threshold:
        return 'Low'
    elif avg_pollution <= moderate_threshold:
        return 'Moderate'
    else:
        return 'High'

df_scaled['pollution_category'] = df_scaled['average_pollution'].apply(categorize_pollution)

# Display the count of each category
print("\nDistribution of Pollution Categories:")
print(df_scaled['pollution_category'].value_counts())

# Visualize the distribution of the new categories
plt.figure(figsize=(8, 6))
sns.countplot(x='pollution_category', data=df_scaled, hue='pollution_category', palette='viridis', order=['Low', 'Moderate', 'High'], legend=False)
plt.title('Distribution of Pollution Categories')
plt.xlabel('Pollution Level')
plt.ylabel('Count')
plt.show()

# Display the first few rows of the DataFrame with the new category column
print("\nFirst 5 rows of df_scaled with 'pollution_category':")
print(df_scaled.head())

"""## Train Supervised Classifiers

### Subtask:
Train three different supervised classification models: Decision Tree, XGBoost, and a Neural Network, using the prepared dataset and the newly created pollution categories as the target variable.

**Reasoning**:
First, I will separate the features (X) from the target variable (y) in `df_scaled`. Then, I will encode the categorical 'pollution_category' into numerical labels using `LabelEncoder`. Finally, I will split the data into training and testing sets using `train_test_split` to prepare for model training.
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# 1. Separate features (X) and target variable (y)
X = df_scaled[numerical_cols] # Features are the scaled numerical air quality metrics
y = df_scaled['pollution_category'] # Target variable is the pollution category

# 2. Encode the categorical target variable
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

print("Original pollution categories:", y.unique())
print("Encoded pollution labels:", label_encoder.classes_)
print("First 5 encoded target values:", y_encoded[:5])

# 3. Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

print(f"\nShape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

"""**Reasoning**:
Now that the data is prepared, I will train the three specified supervised classification models: Decision Tree, XGBoost, and a Neural Network. Each model will be instantiated with a `random_state` for reproducibility and then trained using the `X_train` and `y_train` datasets.


"""

from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.neural_network import MLPClassifier

# 4. Train a Decision Tree Classifier
dt_classifier = DecisionTreeClassifier(random_state=42)
dt_classifier.fit(X_train, y_train)
print("Decision Tree Classifier trained successfully.")

# 5. Train an XGBoost Classifier
xgb_classifier = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss', random_state=42)
xgb_classifier.fit(X_train, y_train)
print("XGBoost Classifier trained successfully.")

# 6. Train a Neural Network Classifier
# Using default hidden_layer_sizes=(100,) and increased max_iter to ensure convergence
mlp_classifier = MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=1000, random_state=42, early_stopping=True, validation_fraction=0.1)
mlp_classifier.fit(X_train, y_train)
print("Neural Network Classifier trained successfully.")

"""**Reasoning**:
The previous code produced a `UserWarning` regarding the deprecated `use_label_encoder` parameter in `XGBClassifier`. I will remove this parameter as it is no longer needed and will prevent future warnings.


"""

from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.neural_network import MLPClassifier

# 4. Train a Decision Tree Classifier
dt_classifier = DecisionTreeClassifier(random_state=42)
dt_classifier.fit(X_train, y_train)
print("Decision Tree Classifier trained successfully.")

# 5. Train an XGBoost Classifier
xgb_classifier = XGBClassifier(eval_metric='mlogloss', random_state=42) # Removed use_label_encoder
xgb_classifier.fit(X_train, y_train)
print("XGBoost Classifier trained successfully.")

# 6. Train a Neural Network Classifier
# Using default hidden_layer_sizes=(100,) and increased max_iter to ensure convergence
mlp_classifier = MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=1000, random_state=42, early_stopping=True, validation_fraction=0.1)
mlp_classifier.fit(X_train, y_train)
print("Neural Network Classifier trained successfully.")

"""## Evaluate Model Performance

### Subtask:
Evaluate the performance of each trained supervised classifier using standard metrics such as Accuracy, F1-score, and a confusion matrix. Generate plots for confusion matrices to visualize classification results for each model.

**Reasoning**:
I need to import the necessary metrics from `sklearn.metrics` for model evaluation, specifically `accuracy_score`, `f1_score`, `confusion_matrix`, and `ConfusionMatrixDisplay`.
"""

from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

print("Imported accuracy_score, f1_score, confusion_matrix, ConfusionMatrixDisplay, and matplotlib.pyplot.")

"""**Reasoning**:
Now that the necessary evaluation metrics are imported, I will evaluate the Decision Tree Classifier by making predictions on the test set, calculating accuracy and F1-score, and plotting its confusion matrix using the original category names.


"""

print("\n--- Evaluating Decision Tree Classifier ---")
y_pred_dt = dt_classifier.predict(X_test)

accuracy_dt = accuracy_score(y_test, y_pred_dt)
f1_dt = f1_score(y_test, y_pred_dt, average='weighted')

print(f"Decision Tree Accuracy: {accuracy_dt:.4f}")
print(f"Decision Tree F1-score (weighted): {f1_dt:.4f}")

cm_dt = confusion_matrix(y_test, y_pred_dt)
disp_dt = ConfusionMatrixDisplay(confusion_matrix=cm_dt, display_labels=label_encoder.classes_)

plt.figure(figsize=(8, 6))
disp_dt.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix for Decision Tree Classifier')
plt.show()

"""**Reasoning**:
Following the evaluation of the Decision Tree Classifier, I will now evaluate the XGBoost Classifier by making predictions on the test set, calculating accuracy and F1-score, and plotting its confusion matrix.


"""

print(
"\n--- Evaluating XGBoost Classifier ---")
y_pred_xgb = xgb_classifier.predict(X_test)

accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
f1_xgb = f1_score(y_test, y_pred_xgb, average='weighted')

print(f"XGBoost Accuracy: {accuracy_xgb:.4f}")
print(f"XGBoost F1-score (weighted): {f1_xgb:.4f}")

cm_xgb = confusion_matrix(y_test, y_pred_xgb)
disp_xgb = ConfusionMatrixDisplay(confusion_matrix=cm_xgb, display_labels=label_encoder.classes_)

plt.figure(figsize=(8, 6))
disp_xgb.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix for XGBoost Classifier')
plt.show()

"""**Reasoning**:
Following the evaluation of the XGBoost Classifier, I will now evaluate the Neural Network Classifier by making predictions on the test set, calculating accuracy and F1-score, and plotting its confusion matrix.


"""

print("\n--- Evaluating Neural Network Classifier ---")
y_pred_mlp = mlp_classifier.predict(X_test)

accuracy_mlp = accuracy_score(y_test, y_pred_mlp)
f1_mlp = f1_score(y_test, y_pred_mlp, average='weighted')

print(f"Neural Network Accuracy: {accuracy_mlp:.4f}")
print(f"Neural Network F1-score (weighted): {f1_mlp:.4f}")

cm_mlp = confusion_matrix(y_test, y_pred_mlp)
disp_mlp = ConfusionMatrixDisplay(confusion_matrix=cm_mlp, display_labels=label_encoder.classes_)

plt.figure(figsize=(8, 6))
disp_mlp.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix for Neural Network Classifier')
plt.show()

"""## Investigate Anomaly Impact

### Subtask:
Analyze how the identified abnormal pollution patterns (from the DBSCAN step) might affect the robustness of the prediction models. This could involve retraining models on cleaned data or using anomaly scores as features and comparing performance.

**Reasoning**:
I need to filter out the anomalies from `df_scaled` using the `dbscan_label_tuned` column, prepare the data by separating features and target, encode the target variable, and then split the data into training and testing sets for the cleaned dataset.
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# 1. Identify anomalies in df_scaled and create df_cleaned
# Anomalies are labeled as -1 by DBSCAN
df_cleaned = df_scaled[df_scaled['dbscan_label_tuned'] != -1].copy()

print(f"Original DataFrame size: {len(df_scaled)} rows")
print(f"Cleaned DataFrame size (after removing anomalies): {len(df_cleaned)} rows\n")

# 2. Prepare data for the cleaned dataset
# Features are the scaled numerical air quality metrics
X_cleaned = df_cleaned[numerical_cols]
# Target variable is the pollution category
y_cleaned = df_cleaned['pollution_category']

# Encode y_cleaned using the previously fitted label_encoder
# It's important to use the same encoder to maintain consistent labels
y_cleaned_encoded = label_encoder.transform(y_cleaned)

print("Original pollution categories in cleaned data:", y_cleaned.unique())
print("Encoded pollution labels in cleaned data (first 5):", y_cleaned_encoded[:5])

# Split X_cleaned and y_cleaned_encoded into new training and testing sets
X_train_cleaned, X_test_cleaned, y_train_cleaned, y_test_cleaned = train_test_split(
    X_cleaned, y_cleaned_encoded, test_size=0.2, random_state=42
)

print(f"\nShape of X_train_cleaned: {X_train_cleaned.shape}")
print(f"Shape of X_test_cleaned: {X_test_cleaned.shape}")
print(f"Shape of y_train_cleaned: {y_train_cleaned.shape}")
print(f"Shape of y_test_cleaned: {y_test_cleaned.shape}")

"""**Reasoning**:
Now that the data is cleaned and split, I will retrain a Neural Network classifier (`MLPClassifier`) using the cleaned training data (`X_train_cleaned`, `y_train_cleaned`) with the same parameters as the original model to assess the impact of anomaly removal.


"""

from sklearn.neural_network import MLPClassifier

# Retrain the Neural Network classifier on the cleaned data
# Instantiate a new MLPClassifier with the same parameters as mlp_classifier
mlp_classifier_cleaned = MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=1000, random_state=42, early_stopping=True, validation_fraction=0.1)
mlp_classifier_cleaned.fit(X_train_cleaned, y_train_cleaned)

print("Neural Network Classifier trained successfully on cleaned data.")

"""**Reasoning**:
Now that the Neural Network classifier has been retrained on the cleaned data, I need to evaluate its performance using accuracy, F1-score, and a confusion matrix, as outlined in the instructions.


"""

from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

print("\n--- Evaluating Neural Network Classifier on Cleaned Data ---")
y_pred_mlp_cleaned = mlp_classifier_cleaned.predict(X_test_cleaned)

accuracy_mlp_cleaned = accuracy_score(y_test_cleaned, y_pred_mlp_cleaned)
f1_mlp_cleaned = f1_score(y_test_cleaned, y_pred_mlp_cleaned, average='weighted')

print(f"Neural Network Accuracy (Cleaned Data): {accuracy_mlp_cleaned:.4f}")
print(f"Neural Network F1-score (weighted, Cleaned Data): {f1_mlp_cleaned:.4f}")

cm_mlp_cleaned = confusion_matrix(y_test_cleaned, y_pred_mlp_cleaned)
disp_mlp_cleaned = ConfusionMatrixDisplay(confusion_matrix=cm_mlp_cleaned, display_labels=label_encoder.classes_)

plt.figure(figsize=(8, 6))
disp_mlp_cleaned.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix for Neural Network Classifier (Cleaned Data)')
plt.show()

"""### Comparison of Neural Network Performance: Original vs. Cleaned Data

**Original Model Performance (trained on data with anomalies):**
*   **Accuracy:** 0.7000
*   **F1-score (weighted):** 0.6723

**Cleaned Model Performance (trained on data with anomalies removed):**
*   **Accuracy:** 0.6667
*   **F1-score (weighted):** 0.6826

**Analysis of Impact:**

Removing the anomalies from the dataset resulted in a slight decrease in accuracy (from 0.7000 to 0.6667) but a slight increase in the weighted F1-score (from 0.6723 to 0.6826) for the Neural Network Classifier.

*   **Accuracy:** The drop in accuracy suggests that some of the points initially classified as 'anomalies' by DBSCAN might have been correctly handled by the original model, or their removal slightly altered the class distribution in a way that affected overall correct predictions. It's also possible that with a smaller dataset size after cleaning (56 rows vs 100 rows), the model had less data to learn from, which can impact accuracy.

*   **F1-score:** The F1-score is a harmonic mean of precision and recall, often more informative than accuracy, especially in multi-class classification or imbalanced datasets. A slight increase in F1-score for the cleaned data suggests that while the overall accuracy might have slightly dropped, the model on cleaned data might be achieving a better balance between precision and recall for each class, or performing better on the minority classes, leading to a more robust classification, even with fewer data points. This could indicate that removing the most extreme outliers helped in creating more distinct class boundaries, even if it slightly reduced the total number of correct predictions.

**Conclusion:**

The impact of removing anomalies is nuanced. While overall accuracy saw a minor dip, the F1-score improved slightly, indicating potentially more balanced and robust predictions across categories. This highlights that 'anomalies' are not always simply 'bad data' but can represent rare but valid occurrences that, when removed, can alter the model's learning landscape. For this specific synthetic dataset, the effect was not dramatically positive in terms of overall accuracy, but the F1-score improvement is a positive sign for robustness. Further investigation with larger, real-world datasets and different anomaly detection/handling strategies would provide deeper insights.

## Final Task

### Subtask:
Summarize the findings from the anomaly detection, model training, and evaluation steps. Discuss the insights gained regarding air quality prediction and the impact of anomaly detection on model robustness.

## Summary:

### Q&A

**Summarize the findings from the anomaly detection, model training, and evaluation steps.**
From the anomaly detection step, it was found that after tuning DBSCAN parameters (eps=1.5, min_samples=3), 44 out of 100 data points were identified as anomalies. In model training and evaluation, three classification models were trained and evaluated on pollution categories ('Low', 'Moderate', 'High'). The Neural Network achieved the highest performance on the original dataset (Accuracy: 0.7000, F1-score: 0.6723), followed by XGBoost (Accuracy: 0.5500, F1-score: 0.4261), and then the Decision Tree (Accuracy: 0.4000, F1-score: 0.3179).

**Discuss the insights gained regarding air quality prediction and the impact of anomaly detection on model robustness.**
Insights regarding air quality prediction show that even with a limited synthetic dataset, machine learning models can learn to categorize pollution levels. The Neural Network demonstrated the strongest predictive capability among the tested models. The impact of anomaly detection on model robustness was nuanced: retraining the Neural Network on data with anomalies removed led to a slight decrease in accuracy (from 0.7000 to 0.6667) but a slight increase in weighted F1-score (from 0.6723 to 0.6826). This suggests that while removing anomalies might sometimes reduce overall correct predictions (accuracy), it could lead to a more balanced performance across classes (F1-score), potentially improving the model's robustness by reducing bias from outliers.

### Data Analysis Key Findings

*   The initial dataset required the creation of dummy data due to a `FileNotFoundError`, and the 'Timestamp' column was successfully converted to datetime and set as the DataFrame index.
*   Numerical features were successfully standardized using `StandardScaler`, and missing values were addressed (though none were present in the dummy data).
*   DBSCAN anomaly detection initially failed with default parameters, labeling all points as anomalies. After tuning parameters to `eps=1.5` and `min_samples=3`, **44 anomalies** were identified out of 100 data points.
*   Pollution categories ('Low', 'Moderate', 'High') were created based on the 33rd and 66th percentiles of an `average_pollution` metric. The categories were well-distributed: 33 'Low', 33 'Moderate', and 34 'High' instances.
*   Three classification models were trained and evaluated:
    *   **Decision Tree**: Accuracy of 0.4000 and weighted F1-score of 0.3179.
    *   **XGBoost**: Accuracy of 0.5500 and weighted F1-score of 0.4261.
    *   **Neural Network (original data)**: Achieved the highest performance with an Accuracy of 0.7000 and a weighted F1-score of 0.6723.
*   Removing the 44 detected anomalies reduced the dataset size from 100 to 56 rows. When the Neural Network was retrained on this "cleaned" data, its performance slightly changed:
    *   **Neural Network (cleaned data)**: Accuracy decreased to 0.6667, while the weighted F1-score slightly increased to 0.6826.

### Insights or Next Steps

*   The slight increase in F1-score for the model trained on cleaned data, despite a small drop in accuracy, suggests that anomaly detection can lead to more balanced and potentially robust models by reducing the influence of extreme outliers on class-specific performance.
*   To further validate the impact of anomaly detection, it would be beneficial to conduct similar analyses on a larger, real-world air quality dataset and explore alternative anomaly detection techniques and handling strategies.

# Task
Load the Air Quality Data from `/content/AQI_daily_2024_Manoharpur_Agra_UPPCB_2024.xlsx` into a pandas DataFrame, ensuring it is ready for initial inspection and processing.

## Load Air Quality Data (New Dataset)

### Subtask:
Load the new Air Quality Dataset from `/content/AQI_daily_2024_Manoharpur_Agra_UPPCB_2024.xlsx` into a pandas DataFrame. The data should be ready for initial inspection and processing, including handling any specific parsing needs for Excel files.

**Reasoning**:
I need to load the new Excel dataset into a pandas DataFrame, then display its head and info as specified in the instructions to ensure the data is loaded correctly and understand its structure.
"""

import pandas as pd

# Load the dataset from the specified Excel file path
df_new = pd.read_excel('/content/AQI_daily_2024_Manoharpur_Agra_UPPCB_2024.xlsx')

# Display the first few rows of the DataFrame
print("First 5 rows of the new DataFrame:")
print(df_new.head())

# Display column names, their data types, and non-null counts
print("\nDataFrame Info for the new dataset:")
df_new.info()

"""## Preprocess Data

### Subtask:
Reshape the DataFrame, clean the 'Day' column, create a proper datetime index, and then handle missing values and normalize the AQI feature.

**Reasoning**:
The first step in preprocessing is to convert the wide-format DataFrame `df_new` into a long format using `pd.melt()` to make it suitable for time-series analysis.
"""

df_long = pd.melt(df_new, id_vars='Day', var_name='Month', value_name='AQI')

print("First 5 rows of the long format DataFrame (df_long):")
print(df_long.head())

"""**Reasoning**:
I need to filter non-numeric 'Day' entries, convert 'Day' to integer, create a 'Date' column from 'Day' and 'Month' with the year 2024, convert it to datetime, and set it as the index. Then, I will handle missing AQI values using forward-fill and apply StandardScaler to the 'AQI' column, storing the result in 'AQI_Scaled'. Finally, I'll display the head and info of the processed DataFrame.


"""

from sklearn.preprocessing import StandardScaler

# Filter out non-numeric 'Day' entries and convert to integer
df_long = df_long[pd.to_numeric(df_long['Day'], errors='coerce').notna()]
df_long['Day'] = df_long['Day'].astype(int)

# Create a 'Date' column and set it as index
df_long['Date'] = pd.to_datetime(df_long['Day'].astype(str) + ' ' + df_long['Month'] + ' 2024', format='%d %B %Y')
df_long = df_long.set_index('Date')

# Drop original 'Day' and 'Month' columns as they are now in the index
df_long = df_long.drop(columns=['Day', 'Month'])

# Handle missing values in 'AQI' using forward-fill
print("Missing values in AQI before imputation:", df_long['AQI'].isnull().sum())
df_long['AQI'] = df_long['AQI'].ffill()
# If there are still NaNs at the beginning, back-fill them
df_long['AQI'] = df_long['AQI'].bfill()
print("Missing values in AQI after imputation:", df_long['AQI'].isnull().sum())

# Apply StandardScaler to the 'AQI' column
scaler = StandardScaler()
df_long['AQI_Scaled'] = scaler.fit_transform(df_long[['AQI']])

# Display the first few rows of the processed DataFrame
print("\nFirst 5 rows of the processed df_long:")
print(df_long.head())

# Display DataFrame Info for the processed dataset
print("\nDataFrame Info for the processed df_long:")
df_long.info()

"""**Reasoning**:
The previous code failed because `df_long` was not defined when the preprocessing steps were attempted. I need to re-include the melting step to create `df_long` from `df_new` before proceeding with cleaning, date conversion, missing value handling, and scaling.


"""

from sklearn.preprocessing import StandardScaler

# Re-create df_long as it was not defined in the previous execution context
df_long = pd.melt(df_new, id_vars='Day', var_name='Month', value_name='AQI')

# Filter out non-numeric 'Day' entries and convert to integer
df_long = df_long[pd.to_numeric(df_long['Day'], errors='coerce').notna()]
df_long['Day'] = df_long['Day'].astype(int)

# Create a 'Date' column and set it as index
df_long['Date'] = pd.to_datetime(df_long['Day'].astype(str) + ' ' + df_long['Month'] + ' 2024', format='%d %B %Y')
df_long = df_long.set_index('Date')

# Drop original 'Day' and 'Month' columns as they are now in the index
df_long = df_long.drop(columns=['Day', 'Month'])

# Handle missing values in 'AQI' using forward-fill
print("Missing values in AQI before imputation:", df_long['AQI'].isnull().sum())
df_long['AQI'] = df_long['AQI'].ffill()
# If there are still NaNs at the beginning, back-fill them
df_long['AQI'] = df_long['AQI'].bfill()
print("Missing values in AQI after imputation:", df_long['AQI'].isnull().sum())

# Apply StandardScaler to the 'AQI' column
scaler = StandardScaler()
df_long['AQI_Scaled'] = scaler.fit_transform(df_long[['AQI']])

# Display the first few rows of the processed DataFrame
print("\nFirst 5 rows of the processed df_long:")
print(df_long.head())

# Display DataFrame Info for the processed dataset
print("\nDataFrame Info for the processed df_long:")
df_long.info()

"""## Anomaly Detection (DBSCAN)

### Subtask:
Apply DBSCAN (Density-Based Spatial Clustering of Applications with Noise) to identify abnormal pollution patterns within the preprocessed new dataset. Visualize the detected anomalies.

**Reasoning**:
I will now apply DBSCAN to the `AQI_Scaled` column of the `df_long` DataFrame. I'll initialize DBSCAN with default parameters, store the labels, and then visualize the results on a scatter plot, highlighting anomalies and printing their count.
"""

from sklearn.cluster import DBSCAN
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Initialize DBSCAN model
dbscannew = DBSCAN(eps=0.5, min_samples=5)

# 2. Apply DBSCAN to the AQI_Scaled column
# DBSCAN expects a 2D array, so reshape the series
df_long['dbscan_label_new'] = dbscannew.fit_predict(df_long[['AQI_Scaled']])

# 4. Create a scatter plot to visualize the AQI_Scaled values over time
plt.figure(figsize=(12, 6))
sns.scatterplot(
    x=df_long.index, y='AQI_Scaled', hue='dbscan_label_new', data=df_long,
    palette='viridis', s=100, legend='full'
)

# 5. Add title and axis labels
plt.title('DBSCAN Anomaly Detection on AQI_Scaled Over Time')
plt.xlabel('Date')
plt.ylabel('AQI_Scaled')
plt.grid(True)

# 6. Display the plot
plt.show()

# 7. Print the total count of anomalies detected
num_anomalies_new = len(df_long[df_long['dbscan_label_new'] == -1])
print(f"Number of anomalies detected in the new dataset: {num_anomalies_new}")

"""**Reasoning**:
The previous code failed because `df_long` was not defined when the DBSCAN application was attempted. I need to re-include the data preparation steps to create and preprocess `df_long` before applying DBSCAN, ensuring all operations are within a single execution block.


"""

from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns

# Re-create df_long and preprocess it, as the previous state might have been lost
df_long = pd.melt(df_new, id_vars='Day', var_name='Month', value_name='AQI')

# Filter out non-numeric 'Day' entries and convert to integer
df_long = df_long[pd.to_numeric(df_long['Day'], errors='coerce').notna()]
df_long['Day'] = df_long['Day'].astype(int)

# Create a 'Date' column and set it as index
df_long['Date'] = pd.to_datetime(df_long['Day'].astype(str) + ' ' + df_long['Month'] + ' 2024', format='%d %B %Y')
df_long = df_long.set_index('Date')

# Drop original 'Day' and 'Month' columns as they are now in the index
df_long = df_long.drop(columns=['Day', 'Month'])

# Handle missing values in 'AQI' using forward-fill
df_long['AQI'] = df_long['AQI'].ffill()
# If there are still NaNs at the beginning, back-fill them
df_long['AQI'] = df_long['AQI'].bfill()

# Apply StandardScaler to the 'AQI' column
scaler = StandardScaler()
df_long['AQI_Scaled'] = scaler.fit_transform(df_long[['AQI']])

# 1. Initialize DBSCAN model
dbscannew = DBSCAN(eps=0.5, min_samples=5)

# 2. Apply DBSCAN to the AQI_Scaled column
# DBSCAN expects a 2D array, so reshape the series
df_long['dbscan_label_new'] = dbscannew.fit_predict(df_long[['AQI_Scaled']])

# 4. Create a scatter plot to visualize the AQI_Scaled values over time
plt.figure(figsize=(12, 6))
sns.scatterplot(
    x=df_long.index, y='AQI_Scaled', hue='dbscan_label_new', data=df_long,
    palette='viridis', s=100, legend='full'
)

# 5. Add title and axis labels
plt.title('DBSCAN Anomaly Detection on AQI_Scaled Over Time')
plt.xlabel('Date')
plt.ylabel('AQI_Scaled')
plt.grid(True)

# 6. Display the plot
plt.show()

# 7. Print the total count of anomalies detected
num_anomalies_new = len(df_long[df_long['dbscan_label_new'] == -1])
print(f"Number of anomalies detected in the new dataset: {num_anomalies_new}")

"""**Reasoning**:
The previous code failed with a `ValueError: day is out of range for month` during date conversion, indicating that some combinations of 'Day' and 'Month' create invalid dates (e.g., February 31st). To handle these gracefully, I will use `errors='coerce'` in `pd.to_datetime` to convert invalid dates to `NaT` (Not a Time), and then remove these `NaT` entries before setting the index and proceeding with DBSCAN.


"""

from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd # Ensure pandas is imported as it was used implicitly via df_new

# Re-create df_long and preprocess it, as the previous state might have been lost
df_long = pd.melt(df_new, id_vars='Day', var_name='Month', value_name='AQI')

# Filter out non-numeric 'Day' entries and convert to integer
df_long = df_long[pd.to_numeric(df_long['Day'], errors='coerce').notna()]
df_long['Day'] = df_long['Day'].astype(int)

# Create a 'Date' column
df_long['Date'] = pd.to_datetime(
    df_long['Day'].astype(str) + ' ' + df_long['Month'] + ' 2024',
    format='%d %B %Y',
    errors='coerce' # Convert invalid dates to NaT
)

# Drop rows where Date is NaT (invalid dates)
df_long.dropna(subset=['Date'], inplace=True)

# Set 'Date' as index
df_long = df_long.set_index('Date')

# Drop original 'Day' and 'Month' columns as they are now in the index
df_long = df_long.drop(columns=['Day', 'Month'])

# Handle missing values in 'AQI' using forward-fill
print("Missing values in AQI before imputation:", df_long['AQI'].isnull().sum())
df_long['AQI'] = df_long['AQI'].ffill()
# If there are still NaNs at the beginning, back-fill them
df_long['AQI'] = df_long['AQI'].bfill()
print("Missing values in AQI after imputation:", df_long['AQI'].isnull().sum())

# Apply StandardScaler to the 'AQI' column
scaler = StandardScaler()
df_long['AQI_Scaled'] = scaler.fit_transform(df_long[['AQI']])

# Display DataFrame Info for the processed dataset
print("\nDataFrame Info for the processed df_long:")
df_long.info()

# 1. Initialize DBSCAN model
dbscannew = DBSCAN(eps=0.5, min_samples=5)

# 2. Apply DBSCAN to the AQI_Scaled column
# DBSCAN expects a 2D array, so reshape the series
df_long['dbscan_label_new'] = dbscannew.fit_predict(df_long[['AQI_Scaled']])

# 4. Create a scatter plot to visualize the AQI_Scaled values over time
plt.figure(figsize=(12, 6))
sns.scatterplot(
    x=df_long.index, y='AQI_Scaled', hue='dbscan_label_new', data=df_long,
    palette='viridis', s=100, legend='full'
)

# 5. Add title and axis labels
plt.title('DBSCAN Anomaly Detection on AQI_Scaled Over Time')
plt.xlabel('Date')
plt.ylabel('AQI_Scaled')
plt.grid(True)

# 6. Display the plot
plt.show()

# 7. Print the total count of anomalies detected
num_anomalies_new = len(df_long[df_long['dbscan_label_new'] == -1])
print(f"Number of anomalies detected in the new dataset: {num_anomalies_new}")

import pandas as pd

# Create a dictionary to store the results for the new dataset
comparison_data_new = {
    'Model': ['Decision Tree (New Data)', 'XGBoost (New Data)', 'Neural Network (New Data)',
              'Neural Network (Cleaned New Data)']
}

# Add accuracy scores for the new dataset
comparison_data_new['Accuracy'] = [
    accuracy_dt_new,
    accuracy_xgb_new,
    accuracy_mlp_new,
    accuracy_mlp_cleaned_new
]

# Add F1-scores for the new dataset
comparison_data_new['F1-score (weighted)'] = [
    f1_dt_new,
    f1_xgb_new,
    f1_mlp_new,
    f1_mlp_cleaned_new
]

# Create the DataFrame
comparison_df_new = pd.DataFrame(comparison_data_new)

# Display the comparison table
print("\n--- Model Performance Comparison (Second Dataset) ---")
display(comparison_df_new)

import pandas as pd

# Create a dictionary to store the results
comparison_data = {
    'Model': ['Decision Tree (Original Data)', 'XGBoost (Original Data)', 'Neural Network (Original Data)',
              'Neural Network (Cleaned Data)']
}

# Add accuracy scores
comparison_data['Accuracy'] = [
    accuracy_dt,
    accuracy_xgb,
    accuracy_mlp,
    accuracy_mlp_cleaned
]

# Add F1-scores
comparison_data['F1-score (weighted)'] = [
    f1_dt,
    f1_xgb,
    f1_mlp,
    f1_mlp_cleaned
]

# Create the DataFrame
comparison_df = pd.DataFrame(comparison_data)

# Display the comparison table
print("\n--- Model Performance Comparison (First Dataset) ---")
display(comparison_df)

"""## Create Pollution Categories

### Subtask:
Based on pollution level features from the new dataset, create discrete pollution categories: 'Low', 'Moderate', and 'High'. This will transform the problem into a multi-class classification task. Visualize the distribution of these new categories.

**Reasoning**:
I need to define pollution categories for the new dataset based on the `AQI_Scaled` column. I will calculate an average pollution metric from the `AQI_Scaled` column and then use quantiles to define 'Low', 'Moderate', and 'High' thresholds for this metric.
"""

import numpy as np

# Define thresholds using quantiles for 'Low', 'Moderate', and 'High' categories
low_threshold_new = df_long['AQI_Scaled'].quantile(0.33)
moderate_threshold_new = df_long['AQI_Scaled'].quantile(0.66)

print(f"Low pollution threshold (33rd percentile): {low_threshold_new:.2f}")
print(f"Moderate pollution threshold (66th percentile): {moderate_threshold_new:.2f}")

"""**Reasoning**:
Now that the thresholds are defined, I will categorize the 'AQI_Scaled' into 'Low', 'Moderate', and 'High' and store these categories in a new column. Then, I will visualize the distribution of these categories using a count plot.


"""

import matplotlib.pyplot as plt
import seaborn as sns

# Create 'pollution_category_new' based on thresholds
def categorize_pollution_new(aqi_scaled):
    if aqi_scaled <= low_threshold_new:
        return 'Low'
    elif aqi_scaled <= moderate_threshold_new:
        return 'Moderate'
    else:
        return 'High'

df_long['pollution_category_new'] = df_long['AQI_Scaled'].apply(categorize_pollution_new)

# Display the count of each category
print("\nDistribution of New Pollution Categories:")
print(df_long['pollution_category_new'].value_counts())

# Visualize the distribution of the new categories
plt.figure(figsize=(8, 6))
sns.countplot(x='pollution_category_new', data=df_long, hue='pollution_category_new', palette='viridis', order=['Low', 'Moderate', 'High'], legend=False)
plt.title('Distribution of New Pollution Categories')
plt.xlabel('Pollution Level')
plt.ylabel('Count')
plt.show()

# Display the first few rows of the DataFrame with the new category column
print("\nFirst 5 rows of df_long with 'pollution_category_new':")
print(df_long.head())

"""## Train Supervised Classifiers

### Subtask:
Train three different supervised classification models: Decision Tree, XGBoost, and a Neural Network, using the prepared new dataset and the newly created pollution categories as the target variable.

**Reasoning**:
First, I will separate the features (`AQI_Scaled`) from the target variable (`pollution_category_new`) in `df_long`. Then, I will encode the categorical target into numerical labels using `LabelEncoder` and split the data into training and testing sets using `train_test_split` to prepare for model training.
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# 1. Separate features (X_new) and target variable (y_new)
X_new = df_long[['AQI_Scaled']] # Features is the scaled AQI metric
y_new = df_long['pollution_category_new'] # Target variable is the new pollution category

# 2. Encode the categorical target variable
label_encoder_new = LabelEncoder()
y_new_encoded = label_encoder_new.fit_transform(y_new)

print("Original pollution categories for new data:", y_new.unique())
print("Encoded pollution labels for new data:", label_encoder_new.classes_)
print("First 5 encoded target values for new data:", y_new_encoded[:5])

# 3. Split data into training and testing sets
X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(X_new, y_new_encoded, test_size=0.2, random_state=42)

print(f"\nShape of X_train_new: {X_train_new.shape}")
print(f"Shape of X_test_new: {X_test_new.shape}")
print(f"Shape of y_train_new: {y_train_new.shape}")
print(f"Shape of y_test_new: {y_test_new.shape}")

"""**Reasoning**:
Now that the data is prepared, I will train the three specified supervised classification models: Decision Tree, XGBoost, and a Neural Network. Each model will be instantiated with a `random_state` for reproducibility and then trained using the `X_train_new` and `y_train_new` datasets.


"""

from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.neural_network import MLPClassifier

# 4. Train a Decision Tree Classifier
dt_classifier_new = DecisionTreeClassifier(random_state=42)
dt_classifier_new.fit(X_train_new, y_train_new)
print("Decision Tree Classifier for new data trained successfully.")

# 5. Train an XGBoost Classifier
xgb_classifier_new = XGBClassifier(eval_metric='mlogloss', random_state=42)
xgb_classifier_new.fit(X_train_new, y_train_new)
print("XGBoost Classifier for new data trained successfully.")

# 6. Train a Neural Network Classifier
mlp_classifier_new = MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=1000, random_state=42, early_stopping=True, validation_fraction=0.1)
mlp_classifier_new.fit(X_train_new, y_train_new)
print("Neural Network Classifier for new data trained successfully.")

"""## Evaluate Model Performance

### Subtask:
Evaluate the performance of each trained supervised classifier using standard metrics such as Accuracy, F1-score, and a confusion matrix. Generate plots for confusion matrices to visualize classification results for each model, using the new dataset's evaluation results.

**Reasoning**:
Now that the necessary evaluation metrics are imported, I will evaluate the Decision Tree Classifier for the new dataset by making predictions on the test set, calculating accuracy and F1-score, and plotting its confusion matrix using the new dataset's category names.
"""

print("\n--- Evaluating Decision Tree Classifier (New Data) ---")
y_pred_dt_new = dt_classifier_new.predict(X_test_new)

accuracy_dt_new = accuracy_score(y_test_new, y_pred_dt_new)
f1_dt_new = f1_score(y_test_new, y_pred_dt_new, average='weighted')

print(f"Decision Tree Accuracy (New Data): {accuracy_dt_new:.4f}")
print(f"Decision Tree F1-score (weighted, New Data): {f1_dt_new:.4f}")

cm_dt_new = confusion_matrix(y_test_new, y_pred_dt_new)
disp_dt_new = ConfusionMatrixDisplay(confusion_matrix=cm_dt_new, display_labels=label_encoder_new.classes_)

plt.figure(figsize=(8, 6))
disp_dt_new.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix for Decision Tree Classifier (New Data)')
plt.show()

"""**Reasoning**:
Following the evaluation of the Decision Tree Classifier, I will now evaluate the XGBoost Classifier for the new dataset by making predictions on the test set, calculating accuracy and F1-score, and plotting its confusion matrix.


"""

print("\n--- Evaluating XGBoost Classifier (New Data) ---")
y_pred_xgb_new = xgb_classifier_new.predict(X_test_new)

accuracy_xgb_new = accuracy_score(y_test_new, y_pred_xgb_new)
f1_xgb_new = f1_score(y_test_new, y_pred_xgb_new, average='weighted')

print(f"XGBoost Accuracy (New Data): {accuracy_xgb_new:.4f}")
print(f"XGBoost F1-score (weighted, New Data): {f1_xgb_new:.4f}")

cm_xgb_new = confusion_matrix(y_test_new, y_pred_xgb_new)
disp_xgb_new = ConfusionMatrixDisplay(confusion_matrix=cm_xgb_new, display_labels=label_encoder_new.classes_)

plt.figure(figsize=(8, 6))
disp_xgb_new.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix for XGBoost Classifier (New Data)')
plt.show()

"""**Reasoning**:
Following the evaluation of the XGBoost Classifier, I will now evaluate the Neural Network Classifier for the new dataset by making predictions on the test set, calculating accuracy and F1-score, and plotting its confusion matrix.


"""

print("\n--- Evaluating Neural Network Classifier (New Data) ---")
y_pred_mlp_new = mlp_classifier_new.predict(X_test_new)

accuracy_mlp_new = accuracy_score(y_test_new, y_pred_mlp_new)
f1_mlp_new = f1_score(y_test_new, y_pred_mlp_new, average='weighted')

print(f"Neural Network Accuracy (New Data): {accuracy_mlp_new:.4f}")
print(f"Neural Network F1-score (weighted, New Data): {f1_mlp_new:.4f}")

cm_mlp_new = confusion_matrix(y_test_new, y_pred_mlp_new)
disp_mlp_new = ConfusionMatrixDisplay(confusion_matrix=cm_mlp_new, display_labels=label_encoder_new.classes_)

plt.figure(figsize=(8, 6))
disp_mlp_new.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix for Neural Network Classifier (New Data)')
plt.show()

"""## Investigate Anomaly Impact

### Subtask:
Analyze how the identified abnormal pollution patterns (from the DBSCAN step) might affect the robustness of the prediction models using the new dataset. This could involve retraining models on cleaned data or using anomaly scores as features and comparing performance.

**Reasoning**:
I need to filter out anomalies from the `df_long` DataFrame to create `df_cleaned_new`, prepare the features and target variables, encode the target, split the data, retrain the Neural Network classifier on this cleaned data, and then evaluate its performance with accuracy, F1-score, and a confusion matrix.
"""

from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# 1. Create a new DataFrame, df_cleaned_new, by filtering out anomalies
df_cleaned_new = df_long[df_long['dbscan_label_new'] != -1].copy()

print(f"Original new dataset size: {len(df_long)} rows")
print(f"Cleaned new dataset size (after removing anomalies): {len(df_cleaned_new)} rows\n")

# 2. Separate features (X_cleaned_new) and target variable (y_cleaned_new)
X_cleaned_new = df_cleaned_new[['AQI_Scaled']]
y_cleaned_new = df_cleaned_new['pollution_category_new']

# 3. Encode y_cleaned_new using the previously fitted label_encoder_new
y_cleaned_new_encoded = label_encoder_new.transform(y_cleaned_new)

print("Original pollution categories in cleaned new data:", y_cleaned_new.unique())
print("Encoded pollution labels in cleaned new data (first 5):", y_cleaned_new_encoded[:5])

# 4. Split X_cleaned_new and y_cleaned_new_encoded into training and testing sets
X_train_cleaned_new, X_test_cleaned_new, y_train_cleaned_new, y_test_cleaned_new = train_test_split(
    X_cleaned_new, y_cleaned_new_encoded, test_size=0.2, random_state=42
)

print(f"\nShape of X_train_cleaned_new: {X_train_cleaned_new.shape}")
print(f"Shape of X_test_cleaned_new: {X_test_cleaned_new.shape}")
print(f"Shape of y_train_cleaned_new: {y_train_cleaned_new.shape}")
print(f"Shape of y_test_cleaned_new: {y_test_cleaned_new.shape}")

# 5. Retrain a Neural Network classifier on this cleaned training data
mlp_classifier_cleaned_new = MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=1000, random_state=42, early_stopping=True, validation_fraction=0.1)
mlp_classifier_cleaned_new.fit(X_train_cleaned_new, y_train_cleaned_new)

print("\nNeural Network Classifier trained successfully on cleaned new data.")

# 6. Evaluate the performance of this retrained Neural Network classifier
print("\n--- Evaluating Neural Network Classifier on Cleaned New Data ---")
y_pred_mlp_cleaned_new = mlp_classifier_cleaned_new.predict(X_test_cleaned_new)

# 7. Calculate accuracy and F1-score
accuracy_mlp_cleaned_new = accuracy_score(y_test_cleaned_new, y_pred_mlp_cleaned_new)
f1_mlp_cleaned_new = f1_score(y_test_cleaned_new, y_pred_mlp_cleaned_new, average='weighted')

print(f"Neural Network Accuracy (Cleaned New Data): {accuracy_mlp_cleaned_new:.4f}")
print(f"Neural Network F1-score (weighted, Cleaned New Data): {f1_mlp_cleaned_new:.4f}")

# 8. Generate and display a confusion matrix
cm_mlp_cleaned_new = confusion_matrix(y_test_cleaned_new, y_pred_mlp_cleaned_new)
disp_mlp_cleaned_new = ConfusionMatrixDisplay(confusion_matrix=cm_mlp_cleaned_new, display_labels=label_encoder_new.classes_)

plt.figure(figsize=(8, 6))
disp_mlp_cleaned_new.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix for Neural Network Classifier (Cleaned New Data)')
plt.show()

"""### Comparison of Neural Network Performance (New Dataset): Original vs. Cleaned Data

**Original Model Performance (trained on full new data, including anomalies):**
*   **Accuracy:** 0.6892
*   **F1-score (weighted):** 0.6703

**Cleaned Model Performance (trained on new data with anomalies removed):**
*   **Accuracy:** 0.6712
*   **F1-score (weighted):** 0.6553

**Analysis of Impact:**

For the new dataset, removing the anomalies detected by DBSCAN (3 out of 366 data points) resulted in a slight decrease in both accuracy (from 0.6892 to 0.6712) and the weighted F1-score (from 0.6703 to 0.6553) for the Neural Network Classifier. This observation is different from the previous synthetic dataset, where the F1-score slightly increased after anomaly removal.

*   **Accuracy and F1-score:** The small decrease in both metrics suggests that the few anomalies identified in this real-world (or more realistic) dataset might not have been significantly detrimental to the model's performance. It's possible that these points, while outliers in a density-based sense, were not strong enough to distort the overall classification boundaries, or their removal led to a slight loss of information that the model was otherwise leveraging effectively. Given the very small number of anomalies (3 out of 366), their impact on a relatively large dataset might be minimal.

**Conclusion:**

In this new dataset, the removal of anomalies, as identified by DBSCAN with `eps=0.5` and `min_samples=5`, did not significantly improve the Neural Network's performance. In fact, there was a minor degradation in both accuracy and F1-score. This highlights that the impact of anomaly detection on model robustness is highly dependent on the nature of the data, the chosen anomaly detection parameters, and the characteristics of the anomalies themselves. Not all outliers are 'bad' data that negatively affect models; some might represent valid, albeit rare, extreme events that models should ideally learn to handle. Further investigation with different anomaly detection thresholds or methods might reveal alternative impacts.

## Final Task

### Subtask:
Summarize the findings from the anomaly detection, model training, and evaluation steps using the new dataset. Discuss the insights gained regarding air quality prediction and the impact of anomaly detection on model robustness.

## Summary:

### Q&A
The impact of anomaly detection on model robustness for the new dataset was observed to be minor. Removing the 3 identified anomalies unexpectedly led to a slight decrease in the Neural Network classifier's performance (accuracy dropped from 0.6892 to 0.6712, and F1-score from 0.6703 to 0.6553). This suggests that the anomalies, while outliers, were not significantly detrimental to the model or may have represented valuable rare events. Regarding air quality prediction, simpler models like Decision Tree and XGBoost achieved perfect prediction (accuracy and F1-score of 1.0000) for the defined pollution categories ('Low', 'Moderate', 'High') on the test set of the new dataset, outperforming the Neural Network (accuracy 0.6892).

### Data Analysis Key Findings
*   A new air quality dataset from `/content/AQI_daily_2024_Manoharpur_Agra_UPPCB_2024.xlsx` was loaded, containing 41 entries and 13 columns. Initial inspection indicated the presence of missing values.
*   The dataset was preprocessed by reshaping it from a wide to a long format, resulting in 366 daily entries. Missing AQI values (12 initially) were imputed using a combination of forward and backward fill, and the 'AQI' feature was scaled.
*   DBSCAN identified 3 anomalies (outliers) in the scaled AQI data using parameters `eps=0.5` and `min_samples=5`.
*   Three pollution categories ('Low', 'Moderate', 'High') were created based on the 33rd ($-0.56$) and 66th ($0.18$) percentiles of the scaled AQI. The distribution was fairly even: 124 'Low', 123 'High', and 119 'Moderate' entries.
*   **Model Performance on Original Data (New Dataset):**
    *   Decision Tree Classifier achieved an Accuracy of 1.0000 and a weighted F1-score of 1.0000.
    *   XGBoost Classifier achieved an Accuracy of 1.0000 and a weighted F1-score of 1.0000.
    *   Neural Network Classifier achieved an Accuracy of 0.6892 and a weighted F1-score of 0.6703.
*   **Impact of Anomaly Removal on Neural Network:** After removing the 3 identified anomalies, the Neural Network classifier was retrained. Its performance slightly decreased: Accuracy dropped from 0.6892 to 0.6712, and the weighted F1-score dropped from 0.6703 to 0.6553.

### Insights or Next Steps
*   The impact of anomaly detection is highly context-dependent; for this new dataset, removing a small number of DBSCAN-identified anomalies did not improve, but slightly degraded, the Neural Network's predictive performance. This suggests that the anomalies might not have been detrimental or could represent valuable rare events.
*   For predicting air quality categories, simpler models like Decision Tree and XGBoost demonstrated perfect performance on this specific dataset, indicating they might be more suitable or that the Neural Network's architecture/hyperparameters need further optimization for this task.
"""
