# -*- coding: utf-8 -*-
"""Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1viQjQsbk6a5HskyUfB0HpnHaHdV3E6zn
"""



#  Misinformation Detection — Scoped Implementation
#  Uses: LIAR Dataset + TF-IDF + Random Forest
#  Author: Rohan Misra | IPM06134 | Sec-B


# ── CELL 1: Install & Import ─────────────────────────────────────────────────

import pandas as pd
import numpy as np
import re
import warnings
warnings.filterwarnings("ignore")

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (accuracy_score, precision_score,
                             recall_score, f1_score,
                             classification_report, confusion_matrix)
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sns

print("All libraries imported successfully.")


# ── CELL 2: Download LIAR Dataset ────────────────────────────────────────────
# The LIAR dataset has 12,800 labeled political statements.
# Labels: pants-fire, false, barely-true, half-true, mostly-true, true
# We simplify to binary: 0 = Misinformation, 1 = Credible

import urllib.request
import os

BASE_URL = "https://raw.githubusercontent.com/tfs4/liar_dataset/master/"
FILES    = {"train": "train.tsv", "test": "test.tsv", "val": "valid.tsv"}

os.makedirs("liar_data", exist_ok=True)

for split, fname in FILES.items():
    dest = f"liar_data/{fname}"
    if not os.path.exists(dest):
        urllib.request.urlretrieve(BASE_URL + fname, dest)
        print(f"Downloaded {fname}")
    else:
        print(f"Already exists: {fname}")

print("\nDataset ready.")


# ── CELL 3: Load & Inspect ───────────────────────────────────────────────────

COLUMNS = [
    "id", "label", "statement", "subjects", "speaker",
    "speaker_job", "state", "party",
    "barely_true_count", "false_count", "half_true_count",
    "mostly_true_count", "pants_fire_count", "context"
]

train_df = pd.read_csv("liar_data/train.tsv", sep="\t", header=None, names=COLUMNS)
test_df  = pd.read_csv("liar_data/test.tsv",  sep="\t", header=None, names=COLUMNS)
val_df   = pd.read_csv("liar_data/valid.tsv",  sep="\t", header=None, names=COLUMNS)

print("Train shape:", train_df.shape)
print("Test shape: ", test_df.shape)
print("Val shape:  ", val_df.shape)

print("\nLabel distribution (train):")
print(train_df["label"].value_counts())

print("\nSample statements:")
print(train_df[["label", "statement"]].head(5).to_string(index=False))


# ── CELL 4: Binary Label Mapping ─────────────────────────────────────────────
# Misinformation  (0): pants-fire, false, barely-true
# Credible        (1): half-true, mostly-true, true

MISINFO_LABELS  = {"pants-fire", "false", "barely-true"}
CREDIBLE_LABELS = {"half-true", "mostly-true", "true"}

def binarize(label):
    if label in MISINFO_LABELS:
        return 0   # Misinformation
    elif label in CREDIBLE_LABELS:
        return 1   # Credible
    return None    # drop unknowns

for df in [train_df, test_df, val_df]:
    df["binary_label"] = df["label"].apply(binarize)

train_df = train_df.dropna(subset=["binary_label"])
test_df  = test_df.dropna(subset=["binary_label"])
val_df   = val_df.dropna(subset=["binary_label"])

print("Binary label distribution (train):")
print(train_df["binary_label"].value_counts())
print("\n0 = Misinformation  |  1 = Credible")


# ── CELL 5: Text Cleaning ─────────────────────────────────────────────────────

def clean_text(text):
    if not isinstance(text, str):
        return ""
    text = text.lower()
    text = re.sub(r"http\S+|www\S+",  " ", text)   # remove URLs
    text = re.sub(r"[^a-z\s]",        " ", text)   # keep letters only
    text = re.sub(r"\s+",             " ", text)   # collapse whitespace
    return text.strip()

for df in [train_df, test_df, val_df]:
    df["clean_statement"] = df["statement"].apply(clean_text)

print("Sample cleaned statement:")
print(train_df["clean_statement"].iloc[0])


# ── CELL 6: Feature Engineering ──────────────────────────────────────────────
# Feature 1 — TF-IDF on statement text      (captures vocabulary/phrasing)
# Feature 2 — Speaker history counts        (prior credibility signal)
# Feature 3 — Statement length              (sensationalist content tends to be short)

# TF-IDF (top 5000 unigrams + bigrams)
tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1, 2),
                        min_df=2, stop_words="english")

X_train_tfidf = tfidf.fit_transform(train_df["clean_statement"])
X_test_tfidf  = tfidf.transform(test_df["clean_statement"])
X_val_tfidf   = tfidf.transform(val_df["clean_statement"])

# Numeric features: speaker credibility history + statement length
HISTORY_COLS = ["barely_true_count", "false_count", "half_true_count",
                "mostly_true_count", "pants_fire_count"]

def numeric_features(df):
    hist   = df[HISTORY_COLS].fillna(0).values
    length = df["clean_statement"].apply(lambda x: len(x.split())).values.reshape(-1, 1)
    return np.hstack([hist, length])

import scipy.sparse as sp

X_train = sp.hstack([X_train_tfidf, sp.csr_matrix(numeric_features(train_df))])
X_test  = sp.hstack([X_test_tfidf,  sp.csr_matrix(numeric_features(test_df))])
X_val   = sp.hstack([X_val_tfidf,   sp.csr_matrix(numeric_features(val_df))])

y_train = train_df["binary_label"].astype(int).values
y_test  = test_df["binary_label"].astype(int).values
y_val   = val_df["binary_label"].astype(int).values

print(f"Feature matrix shape — Train: {X_train.shape}, Test: {X_test.shape}")


# ── CELL 7: Train Random Forest ───────────────────────────────────────────────

rf_model = RandomForestClassifier(
    n_estimators  = 200,    # 200 trees
    max_depth     = 30,     # prevent overfitting
    min_samples_split = 5,
    class_weight  = "balanced",   # handles class imbalance
    random_state  = 42,
    n_jobs        = -1      # use all CPU cores
)

print("Training Random Forest... (this takes ~1 minute in Colab)")
rf_model.fit(X_train, y_train)
print("Training complete.")


# ── CELL 8: Evaluate on Test Set ─────────────────────────────────────────────

y_pred = rf_model.predict(X_test)

acc  = accuracy_score(y_test,  y_pred)
prec = precision_score(y_test, y_pred)
rec  = recall_score(y_test,    y_pred)
f1   = f1_score(y_test,        y_pred)

print("=" * 45)
print("         MODEL PERFORMANCE — TEST SET")
print("=" * 45)
print(f"  Accuracy  : {acc:.4f}  ({acc*100:.2f}%)")
print(f"  Precision : {prec:.4f}")
print(f"  Recall    : {rec:.4f}")
print(f"  F1 Score  : {f1:.4f}  ({f1*100:.2f}%)")
print("=" * 45)

print("\nDetailed Classification Report:")
print(classification_report(y_test, y_pred,
      target_names=["Misinformation", "Credible"]))


# ── CELL 9: Confusion Matrix Plot ────────────────────────────────────────────

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(7, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Predicted: Misinfo", "Predicted: Credible"],
            yticklabels=["Actual: Misinfo",    "Actual: Credible"])
plt.title("Confusion Matrix — Random Forest Misinformation Detector", fontsize=13, pad=12)
plt.tight_layout()
plt.savefig("confusion_matrix.png", dpi=150)
plt.show()
print("Saved: confusion_matrix.png")


# ── CELL 10: Feature Importance ──────────────────────────────────────────────
# Shows which words/features drive the model's decisions most.

feature_names = (tfidf.get_feature_names_out().tolist() + HISTORY_COLS + ["statement_length"])
importances   = rf_model.feature_importances_

top_idx  = np.argsort(importances)[::-1][:20]
top_feat = [feature_names[i] for i in top_idx]
top_imp  = importances[top_idx]

plt.figure(figsize=(10, 6))
colors = ["#1F4E79" if i < 15 else "#E06B2D" for i in range(20)]
plt.barh(top_feat[::-1], top_imp[::-1], color=colors[::-1])
plt.xlabel("Feature Importance Score")
plt.title("Top 20 Most Influential Features", fontsize=13, pad=12)
plt.tight_layout()
plt.savefig("feature_importance.png", dpi=150)
plt.show()
print("Saved: feature_importance.png")


# ── CELL 11: Risk Score Distribution ─────────────────────────────────────────
# Shows the model's confidence (probability) distribution

y_prob = rf_model.predict_proba(X_test)[:, 1]   # probability of "Credible"

plt.figure(figsize=(9, 5))
plt.hist(y_prob[y_test == 0], bins=40, alpha=0.6,
         color="#C0392B", label="Actual Misinformation")
plt.hist(y_prob[y_test == 1], bins=40, alpha=0.6,
         color="#1F4E79", label="Actual Credible")
plt.axvline(0.5, color="black", linestyle="--", linewidth=1.5, label="Decision Threshold (0.5)")
plt.xlabel("Predicted Probability of Being Credible")
plt.ylabel("Number of Statements")
plt.title("Model Confidence Distribution", fontsize=13, pad=12)
plt.legend()
plt.tight_layout()
plt.savefig("confidence_distribution.png", dpi=150)
plt.show()
print("Saved: confidence_distribution.png")


# ── CELL 12: Live Prediction Function ────────────────────────────────────────
# Test the model on any statement you write yourself.

def predict_statement(statement_text):
    cleaned   = clean_text(statement_text)
    tfidf_vec = tfidf.transform([cleaned])
    length    = np.array([[len(cleaned.split())]])
    history   = np.zeros((1, len(HISTORY_COLS)))   # unknown speaker history
    features  = sp.hstack([tfidf_vec, sp.csr_matrix(np.hstack([history, length]))])

    prediction   = rf_model.predict(features)[0]
    probability  = rf_model.predict_proba(features)[0]

    label = "CREDIBLE" if prediction == 1 else "MISINFORMATION"
    conf  = probability[prediction] * 100

    print(f"\nStatement : {statement_text}")
    print(f"Prediction: {label}")
    print(f"Confidence: {conf:.1f}%")
    print(f"  Misinfo probability : {probability[0]*100:.1f}%")
    print(f"  Credible probability: {probability[1]*100:.1f}%")


# ── TEST IT ───────────────────────────────────────────────────────────────────
predict_statement("The government is secretly putting chemicals in drinking water to control the population.")
predict_statement("The unemployment rate fell to 3.7% last quarter according to the Bureau of Labor Statistics.")
predict_statement("Vaccines cause autism and the CDC is hiding the evidence from the public.")
predict_statement("Scientists have confirmed that climate change is driven primarily by human activity.")